# Generated by Django 2.0.6 on 2018-06-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='author',
            field=models.CharField(default='Nobody', max_length=30),
            preserve_default=False,
        ),
    ]
