# Generated by Django 2.0.6 on 2018-06-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='quest_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
