# Generated by Django 2.0.6 on 2018-06-16 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_comments_quest_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='quest_id',
        ),
    ]
